#  __  __ _____ ____   ____                 _             
# |  \/  |  ___|  _ \ / ___| __ _ _ __ ___ (_)_ __   __ _ 
# | |\/| | |_  | | | | |  _ / _` | '_ ` _ \| | '_ \ / _` |
# | |  | |  _| | |_| | |_| | (_| | | | | | | | | | | (_| |
# |_|  |_|_|   |____/ \____|\__,_|_| |_| |_|_|_| |_|\__, |
#                                                    |___/
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

kill-message: Change the kill message
kill-money-ammount: 12